# Generated by Django 4.2.10 on 2024-03-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_add',
            name='brand',
        ),
        migrations.AddField(
            model_name='sales_add',
            name='rate',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_add',
            name='type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rental', 'Rental')], default=332, max_length=50),
            preserve_default=False,
        ),
    ]
