# Generated by Django 4.2.10 on 2024-03-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_remove_sales_add_brand_sales_add_rate_sales_add_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_add',
            name='item',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Tablets', 'Tablets')], max_length=50),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(default=0, max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('expo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.sales_add')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.customer')),
            ],
        ),
    ]
