# Generated by Django 4.2.10 on 2024-03-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_sales_add_item_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='expo_code',
            new_name='sale',
        ),
    ]
