# Generated by Django 4.2.10 on 2024-03-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_rename_expo_code_cart_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_add',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
