# Generated by Django 4.2.10 on 2024-03-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_sales_add_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentschedule',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
