# Generated by Django 4.2.10 on 2024-03-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_appointmentschedule_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='location',
            field=models.CharField(default='kerala', max_length=50),
        ),
    ]
