# Generated by Django 4.2.10 on 2024-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_add',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
